cp ./photos/1.jpg ./chosen/
cp ./photos/2.jpg ./chosen/
cp ./photos/3.jpg ./chosen/
cp ./photos/5.jpg ./chosen/
cp ./photos/8.jpg ./chosen/
cp ./photos/9.jpg ./chosen/
cp ./photos/11.jpg ./chosen/
cp ./photos/13.jpg ./chosen/
cp ./photos/14.jpg ./chosen/
cp ./photos/17.jpg ./chosen/
cp ./photos/19.jpg ./chosen/
cp ./photos/20.jpg ./chosen/
cp ./photos/23.jpg ./chosen/
cp ./photos/27.jpg ./chosen/
cp ./photos/28.jpg ./chosen/
cp ./photos/29.jpg ./chosen/
cp ./photos/33.jpg ./chosen/
cp ./photos/37.jpg ./chosen/
cp ./photos/38.jpg ./chosen/
cp ./photos/40.jpg ./chosen/
cp ./photos/43.jpg ./chosen/
cp ./photos/49.jpg ./chosen/
cp ./photos/50.jpg ./chosen/
cp ./photos/51.jpg ./chosen/
cp ./photos/55.jpg ./chosen/
cp ./photos/57.jpg ./chosen/
cp ./photos/60.jpg ./chosen/
cp ./photos/62.jpg ./chosen/
cp ./photos/65.jpg ./chosen/
cp ./photos/70.jpg ./chosen/
cp ./photos/76.jpg ./chosen/
cp ./photos/79.jpg ./chosen/
cp ./photos/83.jpg ./chosen/
cp ./photos/85.jpg ./chosen/
cp ./photos/86.jpg ./chosen/
cp ./photos/88.jpg ./chosen/
cp ./photos/89.jpg ./chosen/
cp ./photos/93.jpg ./chosen/
cp ./photos/95.jpg ./chosen/
cp ./photos/97.jpg ./chosen/
cp ./photos/105.jpg ./chosen/
cp ./photos/110.jpg ./chosen/
cp ./photos/113.jpg ./chosen/
cp ./photos/114.jpg ./chosen/
cp ./photos/117.jpg ./chosen/
cp ./photos/130.jpg ./chosen/
cp ./photos/134.jpg ./chosen/
cp ./photos/165.jpg ./chosen/
cp ./photos/179.jpg ./chosen/
cp ./photos/181.jpg ./chosen/
cp ./photos/183.jpg ./chosen/
cp ./photos/184.jpg ./chosen/
cp ./photos/248.jpg ./chosen/
cp ./photos/249.jpg ./chosen/
cp ./photos/253.jpg ./chosen/
cp ./photos/260.jpg ./chosen/
cp ./photos/267.jpg ./chosen/
cp ./photos/269.jpg ./chosen/
cp ./photos/283.jpg ./chosen/
cp ./photos/285.jpg ./chosen/
cp ./photos/287.jpg ./chosen/
cp ./photos/291.jpg ./chosen/
cp ./photos/120.jpg ./chosen/
cp ./photos/147.jpg ./chosen/
cp ./photos/156.jpg ./chosen/
cp ./photos/186.jpg ./chosen/
cp ./photos/189.jpg ./chosen/
cp ./photos/195.jpg ./chosen/
cp ./photos/199.jpg ./chosen/
cp ./photos/201.jpg ./chosen/
cp ./photos/204.jpg ./chosen/
cp ./photos/205.jpg ./chosen/
cp ./photos/206.jpg ./chosen/
cp ./photos/209.jpg ./chosen/
cp ./photos/210.jpg ./chosen/
cp ./photos/211.jpg ./chosen/
cp ./photos/212.jpg ./chosen/
cp ./photos/213.jpg ./chosen/
cp ./photos/215.jpg ./chosen/
cp ./photos/216.jpg ./chosen/
cp ./photos/217.jpg ./chosen/
cp ./photos/221.jpg ./chosen/
cp ./photos/224.jpg ./chosen/
cp ./photos/225.jpg ./chosen/
cp ./photos/226.jpg ./chosen/
cp ./photos/227.jpg ./chosen/
cp ./photos/228.jpg ./chosen/
cp ./photos/229.jpg ./chosen/
cp ./photos/230.jpg ./chosen/
cp ./photos/231.jpg ./chosen/
cp ./photos/232.jpg ./chosen/
cp ./photos/234.jpg ./chosen/
cp ./photos/236.jpg ./chosen/
cp ./photos/237.jpg ./chosen/
cp ./photos/238.jpg ./chosen/
cp ./photos/239.jpg ./chosen/
cp ./photos/240.jpg ./chosen/
cp ./photos/243.jpg ./chosen/
cp ./photos/244.jpg ./chosen/
cp ./photos/294.jpg ./chosen/
cp ./photos/295.jpg ./chosen/
cp ./photos/296.jpg ./chosen/
cp ./photos/297.jpg ./chosen/
cp ./photos/299.jpg ./chosen/
cp ./photos/300.jpg ./chosen/
cp ./photos/302.jpg ./chosen/
cp ./photos/303.jpg ./chosen/
cp ./photos/307.jpg ./chosen/
cp ./photos/315.jpg ./chosen/
cp ./photos/317.jpg ./chosen/
cp ./photos/318.jpg ./chosen/
cp ./photos/319.jpg ./chosen/
cp ./photos/320.jpg ./chosen/
cp ./photos/321.jpg ./chosen/
